<!DOCTYPE html>
<html>
    <head>
    	<meta charset="UTF-8">
        <title><?php echo $title ?> - SISTEMA CMS</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" >

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	    
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" ></script>

        <style type="text/css">
        	html {
        		position: relative;
		        min-height: 100%;
		    }
		    body {
		        margin-bottom: 60px;
		    }
		    .footer {
		        position: absolute;
		        bottom: 0;
		        width: 100%;
		        height: 60px;
		        line-height: 60px;
		        background-color: #f5f5f5;
		    }

		    .container {
		        width: auto;
		        max-width: 680px;
		        padding: 0 15px;
		    }
        </style>
       	
    </head>
    <body class="text-center" >