
<?php include(__TEMPLATE__.'/layout/header.phtml'); ?>

	<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark border-bottom box-shadow">
		<h5 class="my-0 mr-md-auto font-weight-normal text-white">Sistema CMS</h5>
		<nav class="my-2 my-md-0 mr-md-3">
			<a class="p-2 text-white" href="#">Usuario</a>
			<a class="p-2 text-white" href="#">Post</a>
		</nav>
		<a class="btn btn-outline-danger text-white" id="deslogar">Sair</a>
	</div>
