<?php
$title = 'Login';
?>

<?php include(__TEMPLATE__.'/layout/header.phtml'); ?>

<style type="text/css">
    html,
    body {
        height: 100%;
    }

    body {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: center;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }
    .form-signin .checkbox {
        font-weight: 400;
    }
    .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>

<div class="form-signin" id="login-form">
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>

    <h5 id="errolog" class="alert alert-danger" hidden >Usuário/senha inválida(s)!</h2>

    <label for="usuario" class="sr-only">Usuario</label>
    <input type="text" id="usuario" class="form-control" placeholder="Usuario" required="" autofocus="">

    <label for="senha" class="sr-only">Senha</label>
    <input type="password" id="senha" class="form-control" placeholder="Senha" required="">

    <button class="btn btn-lg btn-primary btn-block" id="btn-login" >Acessar</button>
    
</div>

<script>
    $('document').ready(function(){
        
        $("#btn-login").click( function(){
            var usuario = $("#usuario").val();
            var senha   = $("#senha").val();

            $("#btn-login").html('Validando ...');
            $("#btn-login").attr("disabled");
            $('#errolog').attr('hidden'); //Esconde o elemento com id errolog

            $.ajax({
                type : 'POST',
                url  : '/logar',
                data : {usuario: usuario, senha: senha},
                dataType: 'json',
                success:  function(response) { 
                    $("#btn-login").html('Acessar');
                    $('#btn-login').removeAttr('disabled');

                    if(response){ 
                        $("#login-alert").css('display', 'none');

                        top.location = '/';

                    }else{
                        $('#errolog').removeAttr('hidden');

                    }
                },
                error : function(response){
                    $("#btn-login").html('Acessar');
                    $('#errolog').removeAttr('hidden');
                    $('#btn-login').removeAttr('disabled');
                }
            });
        });
    
    });
</script>

<?php include(__TEMPLATE__.'/layout/footer.phtml'); ?>